language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.6.2

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.6.2 LAZ_OPT="--os=linux --cpu=i386"
    - os: linux
      env: LAZ_VER=1.6.2 LAZ_OPT="--os=linux --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.6.2  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.6.2  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
  # Start virtual display server
  - wget https://raw.githubusercontent.com/nielsAD/travis-lazarus/master/.travis.install.py
  - Xvfb $DISPLAY &

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./.travis.install.py

script:
  - lazbuild -r RXXPacker.lpi

notifications:
  email:
    on_success: false
    on_failure: false
