language: generic
sudo: required
dist: trusty

os:
  - linux

install:
  - sudo DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:jonathonf/lazarus
  - sudo apt-get update
  - sudo apt-get install lazarus fpc

script:
  - cp environmentoptions.xml Utils/RXXPacker/
  - cd Utils/RXXPacker/
  - lazbuild -r --ws=gtk2 --pcp=./ RXXPacker.lpi --verbose

notifications:
  email:
    on_success: false
    on_failure: false
